stages:
  - prepare
  - build

prepare:
  image: eclipse-temurin:21-jdk
  stage: prepare
  allow_failure: true
  script:
    - apt-get update && apt-get install -y graphviz
    - java -jar ./Documentation/ml_pipeline_workflow/plantuml-1.2025.0.jar -tpng ./Documentation/ml_pipeline_workflow/*.puml
  artifacts:
    paths:
      - ./Documentation/ml_pipeline_workflow/*.png

Documentation:
  image: danteev/texlive
  stage: build
  script:
    - latexmk -pdf "Documentation/Project_Milestone/Milestone.tex"
  artifacts:
    paths:
      - Documentation/Project_Milestone/Milestone.pdf
    expire_in: 1 week