stages:
  - prepare
  - build

prepare:
  image: eclipse-temurin:21-jdk
  stage: prepare
  script:
    - apt-get update
    - apt-get install graphviz -y
    - java -jar ./doc/bin/plantuml-1.2025.0.jar -tpng ./doc/projectreport/figures/*.puml
  artifacts:
    paths:
      - ./doc/projectreport/figures/*.png

build:
  image: danteev/texlive
  stage: build
  script:
    - cd ./"Project Milestone"/
    - latexmk -pdf Milestone.tex
  artifacts:
    paths:
      - ./"Project Milestone"/Milestone.pdf
  artifacts:
    paths:
      - ./"Project Milestone"/Milestone.pdf
    expire_in: 1 week
