stages:
#  - prepare
  - Documentation
  - model1
  - model2
  - model3
  - model4
  - test
  - deploy

#prepare:
#  image: eclipse-temurin:21-jdk
#  stage: prepare
#  allow_failure: true
#  script:
#    - apt-get update
#    - apt-get install graphviz -y
#    - java -jar ./doc/bin/plantuml-1.2025.0.jar -tpng ./doc/projectreport/figures/*.puml
#  artifacts:
#    paths:
#      - ./doc/projectreport/figures/*.png

Documentation:
  image: danteev/texlive
  stage: build
  script:
    - cd "./Documentation"
    - for file in *.tex; do latexmk -pdf "$file"; done
  artifacts:
    paths:
      - "./Documentation/*.pdf"
    expire_in: 1 week

model1:
  image: alpine:latest
  stage: model1
  script:
    - echo "Processing Model 1..."
    # Add your Model 1 processing commands here

model2:
  image: alpine:latest
  stage: model2
  script:
    - echo "Processing Model 2..."
    # Add your Model 2 processing commands here

model3:
  image: alpine:latest
  stage: model3
  script:
    - echo "Processing Model 3..."
    # Add your Model 3 processing commands here

model4:
  image: alpine:latest
  stage: model4
  script:
    - echo "Processing Model 4..."
    # Add your Model 4 processing commands here


test:
  image: alpine:latest
  stage: test
  script:
    - echo "Running tests..."
    # Replace with your testing commands (e.g., unit tests, integration tests)

deploy:
  image: alpine:latest
  stage: deploy
  script:
    - echo "Deploying application..."
    # Replace with your deployment commands, such as uploading artifacts or updating servers