stages:
  - build
  - model1
  - model2
  - model3
  - model4
  - test
  - gitlog
  - deploy

# Build stage: Build documentation PDFs
build:
  image: danteev/texlive
  stage: build
  script:
    - cd "./Documentation"
    - for file in *.tex; do latexmk -pdf "$file"; done
  artifacts:
    paths:
      - "./Documentation/*.pdf"
    expire_in: 1 week

# Model stages: Placeholder for your model execution
model1:
  image: alpine:latest
  stage: model1
  script:
    - echo "Processing Model 1..."

model2:
  image: alpine:latest
  stage: model2
  script:
    - echo "Processing Model 2..."

model3:
  image: alpine:latest
  stage: model3
  script:
    - echo "Processing Model 3..."

model4:
  image: alpine:latest
  stage: model4
  script:
    - echo "Processing Model 4..."

# Test stage: Placeholder for tests
test:
  image: alpine:latest
  stage: test
  script:
    - echo "Running tests..."

# GitLog stage: Capture commit summary per user
gitlog:
  image: python:3.10
  stage: gitlog
  script:
    - pip install --no-cache-dir --upgrade pip
    - python auto_commit_summary.py
  artifacts:
    paths:
      - commit_summary_*.log
    expire_in: 1 week

# Deploy stage: Placeholder for deployment
deploy:
  image: alpine:latest
  stage: deploy
  script:
    - echo "Deploying application..."
