stages:
  - build
  - model1
  - Ocr_Classification
  - model3
  - model4
  - test
  - deploy

# Build stage: Build documentation PDFs
build:
  image: danteev/texlive
  stage: build
  script:
    - cd Documentation
    - for file in *.tex; do latexmk -pdf "$file"; done
  artifacts:
    paths:
      - Documentation/*.pdf
    expire_in: 1 week

# Model stages: Placeholder for your model execution
model1:
  image: alpine:latest
  stage: model1
  script:
    - echo "Processing Model 1..."

Ocr_Classfication:
  image: python:3.10
  stage: Ocr_Classification
  allow_failue : true
  script:
    - echo "Preparing Ocr Model for preload Test..."
    - cd Src/OCR_Classification_Model/Model
    - pip install --upgrade pip
    - echo "Pip Upgraded"
    - pip install -r requirements.txt
    - echo "Testing File"
    - python test_model.py
  

model3:
  image: alpine:latest
  stage: model3
  script:
    - echo "Processing Model 3..."

model4:
  image: alpine:latest
  stage: model4
  script:
    - echo "Processing Model 4..."

# Test stage: Placeholder for tests
test:
  image: alpine:latest
  stage: test
  script:
    - echo "Running tests..."

# Deploy stage: Placeholder for deployment
deploy:
  image: alpine:latest
  stage: deploy
  script:
    - echo "Deploying application..."
