stages:
  - build
  - model1
  - ocr_classification
  - model3
  - model4
  - test
  - deploy

build:
  stage: build
  image: danteev/texlive
  script:
    - cd Documentation
    - for file in *.tex; do latexmk -pdf "$file"; done
  artifacts:
    paths:
      - Documentation/*.pdf
    expire_in: 1 week

model1:
  stage: model1
  image: alpine:latest
  script:
    - echo "Processing Model 1..."

ocr_classification:
  stage: ocr_classification
  image: python:3.10
  allow_failure: true
  variables:
    PIP_DISABLE_PIP_VERSION_CHECK: "1"
  script:
    # 1) Show where GitLab is running now
    - echo "Workspace root: $CI_PROJECT_DIR"
    - pwd
    - ls -R "$CI_PROJECT_DIR"
    # 2) Change into your model folder (adjust casing if needed)
    - cd "$CI_PROJECT_DIR/Src/OCR_Classification_Model/Model"
    - echo "Now in: $(pwd)"
    - ls -R .
    # 3) Install and test
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - echo "Running classification test"
    - python test_model.py


model3:
  stage: model3
  image: alpine:latest
  script:
    - echo "Processing Model 3..."

model4:
  stage: model4
  image: alpine:latest
  script:
    - echo "Processing Model 4..."

test:
  stage: test
  image: alpine:latest
  script:
    - echo "Running tests..."

deploy:
  stage: deploy
  image: alpine:latest
  script:
    - echo "Deploying application..."
