stages:
  - prepare
  - build

prepare:
  image: eclipse-temurin:21-jdk
  stage: prepare
  allow_failure: true
  script:
    - apt-get update && apt-get install -y graphviz
    - java -jar ./doc/bin/plantuml-1.2025.0.jar -tpng ./doc/projectreport/figures/*.puml
  artifacts:
    paths:
      - ./doc/projectreport/figures/*.png

Documentation:
  image: danteev/texlive
  stage: build
  script:
    - cd Documentation/"Project Milestone"
    - latexmk -pdf Milestone.tex
  artifacts:
    paths:
      - Documentation/"Project Milestone"/*.pdf
    expire_in: 1 week